create footer
peaksoft-school/medcheck-js8 pull request #11
Opened 2023-04-07 11:30 UTC by gulli301185

2023-04-07 12:34 UTC, bayaman77 commented on src/components/footer/Footer.jsx
> +}))
checked 👍

2023-04-07 12:35 UTC, Abdybakieva reviewed
checked

2023-04-07 12:56 UTC, RussoOrmon commented
good

2023-04-10 06:15 UTC, RussoOrmon commented
checked

2023-04-11 09:43 UTC, songhee24 requested changes

2023-04-11 09:43 UTC, songhee24 commented on src/assets/icons/Clock.svg
svg это не компонента прошу называть маленькой буквой

2023-04-12 06:33 UTC, songhee24 approved these changes

2023-04-12 06:33 UTC, merged