Feature/header
peaksoft-school/medcheck-js8 pull request #14
Opened 2023-04-08 08:58 UTC by erkinovakurmanzhan1

2023-04-08 09:21 UTC, Abdybakieva reviewed
checked

2023-04-08 15:38 UTC, RussoOrmon commented
checked

2023-04-08 15:44 UTC, gulli301185 commented on src/components/header/header-styled.js
> +   },
checked!

2023-04-11 09:12 UTC, songhee24 requested changes

2023-04-11 09:16 UTC, erkinovakurmanzhan1 commented on src/components/header/Header.jsx
> +
а вот когда убираем мышку onClick болгондо жабылат

2023-04-11 09:18 UTC, songhee24 commented on src/components/header/Header.jsx
> +
нет нужно закрывать когда мышку полностью убрали и не ждать onClick

2023-04-11 09:18 UTC, songhee24 commented on src/components/header/header-styled.js
> +export const HeaderStyled = styled(AppBar)(() => ({
<img width="533" alt="Screenshot 2023-04-11 at 15 18 25" src="https://user-images.githubusercontent.com/44497623/231114862-cd098357-2a83-47ad-8ec5-45d120eb1710.png">
also you have conflicts

2023-04-12 07:38 UTC, songhee24 approved these changes

2023-04-12 07:38 UTC, merged