create modal UI
peaksoft-school/medcheck-js8 pull request #15
Opened 2023-04-08 15:53 UTC by RussoOrmon

please check code

2023-04-08 16:04 UTC, gulli301185 commented on src/components/UI/ModalUi.jsx
> +   gap: '20px',
good job Ruslan baike!

2023-04-08 16:17 UTC, erkinovakurmanzhan1 commented on src/components/UI/ModalUi.jsx
> +}
checked good!

2023-04-11 09:42 UTC, songhee24 requested changes

2023-04-11 09:42 UTC, songhee24 commented on src/components/UI/ModalUi.jsx
> +         <StyledModalDialog open={open} onClose={onClose}>
вы должны были создать только каркас модалки

2023-04-12 07:47 UTC, songhee24 requested changes

2023-04-12 07:47 UTC, songhee24 commented on src/components/UI/ModalUi.jsx
> +            <DialogContent>
дайте ему children пожалуйста

2023-04-13 12:42 UTC, songhee24 approved these changes

2023-04-13 12:42 UTC, merged