Feature/service
peaksoft-school/medcheck-js8 pull request #20
Opened 2023-04-14 09:41 UTC by gulli301185

2023-04-14 10:18 UTC, erkinovakurmanzhan1 commented on src/components/service/Service.jsx
> +}
checked

2023-04-14 10:18 UTC, Abdybakieva reviewed
checked :)

2023-04-14 12:51 UTC, Kamchybekk commented
![Screen Shot 2023-04-14 at 18 51 41](https://user-images.githubusercontent.com/115062260/232048587-1d5c30d7-617f-45db-b41f-a0f2a1ba06d7.png)

2023-04-14 13:22 UTC, RussoOrmon commented
checked

2023-04-17 09:23 UTC, songhee24 requested changes

2023-04-17 09:23 UTC, songhee24 commented on src/components/UI/select/Sellect.jsx
> +function Sellect() {
so you need to provide props which will render data

2023-04-17 09:23 UTC, songhee24 commented on src/components/card/CardApplication.jsx
> +export default function CardApplication() {
also there we need to collect the form data such phone number and pass to parent component with lifting up pattern

2023-04-17 09:43 UTC, songhee24 requested changes

2023-04-17 09:43 UTC, songhee24 commented on src/components/card/CardApplication.jsx
> +export default function CardApplication() {
please pay attention too

2023-04-17 09:58 UTC, gulli301185 commented on src/components/card/CardApplication.jsx
> +export default function CardApplication() {
sorry)

2023-04-17 11:11 UTC, songhee24 approved these changes

2023-04-17 11:12 UTC, merged