create feedback-slider
peaksoft-school/medcheck-js8 pull request #21
Opened 2023-04-15 04:57 UTC by Abdybakieva

2023-04-15 05:38 UTC, gulli301185 commented on src/components/feedback-slider/FeedbackSlider.jsx
> +         fill: 'url(#paint0_linear_92_5157)',
checked)

2023-04-15 08:29 UTC, RussoOrmon commented
checked

2023-04-15 11:18 UTC, erkinovakurmanzhan1 commented on src/components/feedback-slider/FeedbackSlider.jsx
> +      circle: {
checked

2023-04-17 09:34 UTC, songhee24 requested changes

2023-04-17 09:34 UTC, songhee24 commented on src/components/feedback-slider/FeedbackSlider.jsx
> +                     <Container>
where is the key prop ?

2023-04-17 09:34 UTC, songhee24 commented on src/components/feedback-slider/FeedbackSlider.jsx
> +   const settings = {
need auto play also

2023-04-17 10:46 UTC, songhee24 approved these changes

2023-04-17 10:46 UTC, merged