Feature/appointment table
peaksoft-school/medcheck-js8 pull request #23
Opened 2023-04-17 09:59 UTC by erkinovakurmanzhan1

2023-04-17 10:02 UTC, gulli301185 commented on src/utlis/constants/commons.js
> +   },
checked)

2023-04-17 10:04 UTC, RussoOrmon commented
checked

2023-04-17 10:07 UTC, bayaman77 commented
checked

2023-04-19 06:27 UTC, songhee24 requested changes

2023-04-19 06:27 UTC, songhee24 commented on src/components/UI/AppointmentTable.jsx
> +const AppointmentTable = () => {
опять таки где пропсы ? данные должны приходит через пропсы

2023-04-19 06:27 UTC, songhee24 commented on src/components/UI/AppointmentTable.jsx
> +   const getStatusTitleChangeHandler = (statusTitle) => {
плюс это функция должна быть не внутри компоненты

2023-04-19 07:11 UTC, songhee24 approved these changes

2023-04-19 07:14 UTC, merged