create signIn,signUp
peaksoft-school/medcheck-js8 pull request #29
Opened 2023-04-27 06:55 UTC by gulli301185

2023-04-27 08:59 UTC, RussoOrmon commented
checked

2023-04-27 12:11 UTC, erkinovakurmanzhan1 commented
checked

2023-05-01 07:17 UTC, songhee24 requested changes

2023-05-01 07:17 UTC, songhee24 commented on src/components/login/ChangePassword.jsx
мне кажется по дизайну все компоненты регистрации должны быть модалкой

2023-05-01 09:14 UTC, songhee24 requested changes

2023-05-01 09:14 UTC, songhee24 commented on src/layout/guest/login/ChangePassword.jsx
> +      <ModalUi>
чтобы открывать и закрывать модалку нужно пропсы тоже передавать иначе как они будут открываться

2023-05-01 09:50 UTC, songhee24 approved these changes

2023-05-01 09:51 UTC, merged