done service get Applications and Search input
peaksoft-school/medcheck-js8 pull request #34
Opened 2023-05-02 20:43 UTC by erkinovakurmanzhan1

2023-05-03 05:00 UTC, RussoOrmon commented
checked

2023-05-08 13:19 UTC, songhee24 requested changes

2023-05-08 13:19 UTC, songhee24 commented on src/api/applicationsService.js
> +   return mainApi.get(`/api/applications/getAll?word=${name}`)
а если name не будет /api/applications/getAll?word= запрос вот так будет уходить

2023-05-08 13:19 UTC, songhee24 commented on src/components/UI/Table.jsx
> +                  {boolean ? (
простите меня конечно но что за название boolean ?

2023-05-08 13:19 UTC, songhee24 commented on src/pages/admin/Applications.jsx
> +      dispatch(getApplication())
не уверен что getApplication нужно сохранять все в store

2023-05-08 13:19 UTC, songhee24 commented on src/pages/admin/Applications.jsx
что за папка pages ? у вас уже есть для нее папка containers

2023-05-08 13:19 UTC, songhee24 commented on src/pages/admin/Applications.jsx
> +      dispatch(getGlobalSearch(test))
search data тем более не нужно сохранять во внутрь store все должно быть локально

2023-05-10 08:08 UTC, songhee24 requested changes

2023-05-10 08:08 UTC, songhee24 commented on src/containers/Application.jsx
> +   useEffect(() => {
я заметил что debounced не работает каждый раз когда я печатаю запрос отправляется

2023-05-10 08:08 UTC, songhee24 commented on src/containers/Application.jsx
> +      getApplicationData()
было бы лучше если бы вы использовали один и тот же метод для поиска и для получения всех Applications

2023-05-10 08:08 UTC, songhee24 commented on src/containers/Application.jsx
> +            searchParams.set('word', inputVal)
значеие поиска не надо сохранять в query

2023-05-15 13:20 UTC, Kamchybekk commented
![Screen Shot 2023-05-15 at 19 16 41](https://github.com/peaksoft-school/medcheck-js8/assets/115062260/4485b175-ce19-4d74-bfd5-addc56be40d2)

search иштешит үчүн дагы бир башка функция жазаштын кереги жок getApplications ге эле params кошуңуз мындай кылып: 

![Screen Shot 2023-05-15 at 19 17 54](https://github.com/peaksoft-school/medcheck-js8/assets/115062260/af5ead4b-c663-4ef2-a98c-0878f0d78f56)

params дегенди useSearchParams деп түшүнүп алыптырсын queryUrl ге эле ушундай кылып кошуш керек болчу.

2023-05-17 07:01 UTC, Kamchybekk commented
![Screen Shot 2023-05-17 at 13 00 26](https://github.com/peaksoft-school/medcheck-js8/assets/115062260/51c10dc5-e69a-439a-8d96-7b5a3d06e3a1)
 
Удаленияга модалка чыгарып керек уточняющий

2023-05-17 07:42 UTC, merged