Feature/admin patients
peaksoft-school/medcheck-js8 pull request #47
Opened 2023-06-07 06:02 UTC by gulli301185

2023-06-12 15:51 UTC, songhee24 requested changes

2023-06-12 15:51 UTC, songhee24 commented on src/components/UI/avatar/AvatarUpload.js
> +            <P>Минимальное разрешение 450x600</P>
Минимальное разрешение 450x600 
было бы хорошо сделать проверку 
https://stackoverflow.com/questions/39092859/get-dimensions-of-image-with-react

2023-06-12 15:51 UTC, songhee24 commented on src/components/UI/avatar/AvatarUpload.js
> +                  <img src={avatarUrl} alt="" />
avatarUrl может быть не валидным и для нее тоже проверка была бы кстати

2023-06-12 15:51 UTC, songhee24 commented on src/components/UI/calendar/Calendar.jsx
> +            <DatePicker
у календаря должно быть ограничение ? по каким то датам ? если да то прошу тоже это учитывать

2023-06-12 15:51 UTC, songhee24 commented on src/containers/admin/PatientDetails.jsx
> +         if (name && date && selectedFile) {
```suggestion
         if (name != null && date != null && selectedFile != null) {
```

2023-06-14 16:52 UTC, gulli301185 commented on src/components/UI/avatar/AvatarUpload.js
> +                  <img src={avatarUrl} alt="" />
I couldn't.

2023-06-15 07:40 UTC, merged